### ISSUE TITLE
not working on lora and lycoris

### ISSUE THREAD

**Issue by katana-hydra** [a2569875/lora-prompt-tool#2]
webui version :5ab7f21
Right click but nothing happens on lora and lycoris tab. It works on embedding tab but that's meaningless for me. 
No error message

**Comment by a2569875** [comment]
@katana-hydra sorry, I have tried to reproduce the reported bug on version 5ab7f21, but couldn't replicate it following the steps mentioned in the issue.

**Comment by katana-hydra** [comment]
Thanks for your reply. I've found that your extension works fine with default theme. However it is not compatible with [Kitchen Theme](https://github.com/canisminor1990/sd-webui-kitchen-theme). Please consider add support for this theme extension.

**Comment by katana-hydra** [comment]
Fixed
