### ISSUE TITLE
[Bug] Cannot load original json file, besides lora prompt helper cannot edit lora information

### ISSUE THREAD

**Issue by obs945** [a2569875/lora-prompt-tool#22]
After upgrade to lateset version of lora prompt tool (webui-forge supported version), the menu appeared.
However, original created lora information (trigger words, sample files, etc.,) cannot be loaded.
Besides, I cannot re-add information via lora prompt helper interface even load information from Civitai.

**Comment by obs945** [comment]
As the log showed 
[lora-prompt-tool] Can not find model info file: /Volumes/MX500 SSD/stable-diffusion-webui-forge/models/Lora/Lora/SD Lora/Cloth/Golden_Lehnga_By_Stable_Yogi.json

But actual directory is 
/Volumes/MX500 SSD/stable-diffusion-webui-forge/models/Lora/SD Lora/Cloth/Golden_Lehnga_By_Stable_Yogi.json
There is one redundant "Lora" and this may caused the issue occured.

**Comment by SaturMars** [comment]
try new version plz

**Comment by obs945** [comment]
@SaturMars Thanks for your effort but unfortunately my case still not being solved.
Function menu - OK. The menu showed with no promblem. 
Function menu (edit prompt words) -> LoRA prompt helper -> Download configuration files from CivitAI -> Not OK.

My use case is creating several directory to distinguish the catogary for each Lora
I made "Animateddff" "Pony Lora" "SD Lora" "SDXL Lora" directories under models/Lora
And also created several sub-directories under above listed directories such as "Background" "Cloth" "Enhance" "Face" "Hair". 

For example, there is a Lora file located in 
/Volumes/MX500 SSD/stable-diffusion-webui/models/Lora/Lora/SD Lora/Cloth/edgArmoredCore6Allmind.safetensors
but after use LoRA prompt helper the log showed
[lora-prompt-tool] Can not find model info file: /Volumes/MX500 SSD/stable-diffusion-webui/models/Lora/Lora/SD Lora/Cloth/edgArmoredCore6Allmind.json
There is still one redundant "Lora" in the file path.

**Comment by SaturMars** [comment]
> @SaturMars Thanks for your effort but unfortunately my case still not being solved. Function menu - OK. The menu showed with no promblem. Function menu (edit prompt words) -> LoRA prompt helper -> Download configuration files from CivitAI -> Not OK.
> 
> My use case is creating several directory to distinguish the catogary for each Lora I made "Animateddff" "Pony Lora" "SD Lora" "SDXL Lora" directories under models/Lora And also created several sub-directories under above listed directories such as "Background" "Cloth" "Enhance" "Face" "Hair".
> 
> For example, there is a Lora file located in /Volumes/MX500 SSD/stable-diffusion-webui/models/Lora/Lora/SD Lora/Cloth/edgArmoredCore6Allmind.safetensors but after use LoRA prompt helper the log showed [lora-prompt-tool] Can not find model info file: /Volumes/MX500 SSD/stable-diffusion-webui/models/Lora/Lora/SD Lora/Cloth/edgArmoredCore6Allmind.json There is still one redundant "Lora" in the file path.

The extension is currently working well in my environment (win10,win11), whether it is downloading json directly using the extension or combining with the civitai helper's info file, there is no problem. However, I don't often work on Ubuntu or other Linux distributions, and I will find time to follow up on this soon.

**Comment by obs945** [comment]
The issue was solved in latest commit ([3bfea50](https://github.com/a2569875/lora-prompt-tool/commit/3bfea5094d8bca4a0615d8510314b1ec664b3ee5))
Thanks for @2569875 and @SaturMars hark work.
