### ISSUE TITLE
在將lobe更新至較新版本時，插件會無法發揮作用

### ISSUE THREAD

**Issue by composeweiyun** [a2569875/lora-prompt-tool#5]

**Comment by designrans** [comment]
+1

**Comment by DaisyHunter** [comment]
我是SD新手，请问我的这个[issue](https://github.com/a2569875/lora-prompt-tool/issues/6)是不是也是由于lobe更新造成的呀？

**Comment by a2569875** [comment]
已經有推送[修復補丁](https://github.com/a2569875/lora-prompt-tool/commit/958f4a91f79d5c935221a47b81dd3283e3810956)了，且三個月後並無近一步回報。結以待續。
